LearnTemplates/LearnTemplates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from basicapp import views
from django.conf.urls import include

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^basicapp/',include('basicapp.urls')),
]

LearnTemplates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name = 'basicapp'
urlpatterns = [
    url(r'^relative/$',views.relative,name = 'relative'),
    url(r'^other/$',views.other,name = 'other'),
    url(r'^base/$',views.base,name = 'base'),
]

LearnTemplates/basicapp/models.py
from django.db import models

# Create your models here.

LearnTemplates/basicapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def base(request):
    return render(request,'basicapp/base.html')

def relative(request):
    return render(request,'basicapp/relative_url_tem.html')

LearnTemplates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav ">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link"href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link"href="{% url 'basicapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}


    </div>
  </body>
</html>

LearnTemplates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html "%}
  {% block body_block %}
    <h1>INDEX PAGE!</h1>
    <h1>{{ text|cut:"hello" }} {{ number|add:"99" }}</h1>
  {% endblock %}

LearnTemplates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>Other Page</h1>
    <h3>Example of Template inheritance</h3>
  {% endblock %}

LearnTemplates/templates/basicapp/relative_url_tem.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Relative URL Temp</h1>
    <a href="{% url 'basicapp:other' %}">The Other Page</a>
    <a href="{% url 'admin:index' %}">Admin Page</a>
    <a href="{% url 'index' %}">Index</a>
  </body>
</html>